### ISSUE TITLE
Privacy Manifest File for Castle SDK?

### ISSUE THREAD

**Issue by RGG-jayoung** [castle/castle-ios#109]
Does Castle have a planned release to include a Privacy Manifest file?
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by aalekz** [comment]
Hi @RGG-jayoung!

We're working on including the privacy manifest, should be available in a new version in the next couple of weeks before it becomes a requirement in May.

**Comment by RGG-jayoung** [comment]
@aalekz thank you for the quick response, really appreciate the hustle. Ideally we have plenty of lead time for the May 1st deadline, as we're starting to get the App Store Connect submission warnings. A few weeks lead time gives us enough time for our own internal QA, submission to apple, and back and forth with their review etc. 

If you have any sense of timing, please let me know.

**Comment by aalekz** [comment]
We should be able to have a new release ready at the end of this week or early next week, so that would hopefully give you enough time to prepare.
