### ISSUE TITLE
Unable to add library via Carthage

### ISSUE THREAD

**Issue by anuragt84** [castle/castle-ios#36]
The library can't be added via Carthage because the Project itself fails to build. 

To try and debug the issue, I downloaded the Project and tried to build it locally. This throws up several issues

1. I had to delete the `Info.plist` file in `Build Phases > Copy Bundle Resources` of the Castle target
2. Some files like `Castle + Util.h, CASContext.h/.m, CASReachability.h/.m` weren't added to the Project file
3. `UIKit` needed to be imported for `CASUtils.m` and `CASContext.m` since they are using `UIDevice` and `UIScreen` API

Doing the above three led to a successful build of the framework.

**Comment by anuragt84** [comment]
Do you guys have an estimated time when this will be fixed?

**Comment by aalekz** [comment]
Fixed in #37, merged and ready to go. Thanks for reporting and sorry for any inconvenience! 

Let me know once you've verified!
