### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by RGG-jayoung** [castle/castle-ios#38]
Do you have any plans to support Swift Package manager? Is this something you would accept a PR for?

**Comment by aalekz** [comment]
We're working on adding this to the next release, hopefully available in the next month or so.

**Comment by RGG-jayoung** [comment]
Awesome to hear and thank you for the follow up!

**Comment by aalekz** [comment]
@RGG-jayoung close the issue by accident, will update the issue once it's been implemented and released 🙂

**Comment by aalekz** [comment]
Hey @RGG-jayoung!

Just wanted to inform you that we added support for Swift Package Manager in version 1.0.10.
