### ISSUE TITLE
Archive and ipa geneartion is failing in Xcode

### ISSUE THREAD

**Issue by LekhaPai** [castle/castle-ios#68]
**`**ipatool failed with an exception: #<CmdSpec::NonZeroExitException:** for GeoZip.xcframework and Highwind.Xcframework`**

Castle has been integrated to Project via Pod. 
castle version used is 2.1.1
Xcode version tried on 12.1 and 12.4

On simulator and device the build is running without any issue. But when we try to archive the build is successful, but when we try to export with valid profiles its failing with the above error.

Please provide support for the same.

Log:

Clang option verification failed for bitcode 01 (unrecognized arguments: ..

**Comment by aalekz** [comment]
Hi @LekhaPai,

This seems to be an issue with bitcode. Could you try disabling bitcode by setting `Enable Bitcode` to `NO` in the build settings? Please let me know it that at least circumvents the issue.

**Comment by aalekz** [comment]
If you could also try upgrading Castle to version 2.1.2, that would be great :)

**Comment by LekhaPai** [comment]
Hi @aalekz ,

Thank you for the workaround you mentioned.

We tried the workaround with disabling (Enable Bitcode = NO). Even though the archive is succeeded, when we try to upload to Appstore Connect Testflight, it throws disallowed Framework Error with Castle integrated.

Also, will you please let us know if there is any plan to release the Castle Framework with Bitcode enabled version?
![error](https://user-images.githubusercontent.com/13216239/135453264-6e6f9d12-22f2-41c3-bc22-b85c18d467e4.png)

**Comment by aalekz** [comment]
I've run some tests and can archive and validate an example app using the SDK without seeing the same error that you're seeing. The only difference I can see is that I haven't added any extensions. That leads me to think that it could be caused by the SDK being included in the NotificationExtension. Are you including it in the extension target?

**Comment by aalekz** [comment]
As for bitcode it should work with it enabled, at least in my tests so it might be that it's just a side-effect of it being included in the extension as I described above.
