### ISSUE TITLE
Castle SPM package incompatible with Cocoapods

### ISSUE THREAD

**Issue by appsandwich** [castle/castle-ios#69]
Hi there,

We have an Xcode project that uses both Cocoapods and SwiftPM for package management (the former we consider deprecated and, as such, we'd prefer to import Castle via SwiftPM).

Unfortunately, after upgrading our SwiftPM Castle package from 1.0.10 to 2.1.2, we are unable to build our app (Xcode 12.5).

This is due to the fact that `Castle.h` contains the following check for the `COCOAPODS` preprocessor macro ([link](https://github.com/castle/castle-ios/blob/c07830e1813f9435684a64592962ddc5a26b2c9a/Castle/Public/Castle.h#L18)):

```
#if COCOAPODS
#import <Castle/CastleConfiguration.h>
#else
#import "CastleConfiguration.h"
#endif
```

Because we already integrate other packages via Cocoapods, the `COCOAPODS` macro has been defined, and Xcode tries to build Castle using the `<Castle/CastleConfiguration.h>` import, which errors with a "file not found" message when imported via SPM.

Ideally, this import would be based on a custom macro, defined either via `Castle.podspec` or `Package.swift`.

Thanks in advance.

**Comment by aalekz** [comment]
Thanks for reporting the issue and providing a fix @appsandwich!

Sorry for the wait, everything looks good so I'll merge the pull request shortly. For the sake of documentation I'll describe the reasoning behind having the COCOAPODS check in the first place:

In older versions of Xcode the library wouldn't build when opening the Package.swift directly in xcode, the compiler would complain that it couldn't find the header much like you've described in your issue. This seems to not be the case anymore so no need for the workaround.
