### ISSUE TITLE
SPM build warning: Invalid Exclude SwiftSources: File not found

### ISSUE THREAD

**Issue by tiwoc** [castle/castle-ios#88]
The `Castle` target in `Package.swift` excludes the `SwiftSources` folder which doesn't exist. This leads to the following build warning:

> Invalid Exclude '/Users/redacted/Library/Developer/Xcode/DerivedData/redacted/SourcePackages/checkouts/castle-ios/Castle/SwiftSources': File not found.

Could you please remove `SwiftSources` from the `exclude` array in `Package.swift` to make Castle build cleanly?

**Comment by aalekz** [comment]
Thanks for reporting this issue @tiwoc, I'll create a pull request with a fix this week.

**Comment by aalekz** [comment]
This issue has been fixed in #91 and will be included in the upcoming release.
